//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPOS2.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pos1Entities : DbContext
    {
        public Pos1Entities()
            : base("name=Pos1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGE> AGE { get; set; }
        public virtual DbSet<AGE_TRANSLATION> AGE_TRANSLATION { get; set; }
        public virtual DbSet<BRAND> BRAND { get; set; }
        public virtual DbSet<CASH_BOTTOM_DAY> CASH_BOTTOM_DAY { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CATEGORY_TRANSLATION> CATEGORY_TRANSLATION { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<HERO> HERO { get; set; }
        public virtual DbSet<HERO_TRANSLATION> HERO_TRANSLATION { get; set; }
        public virtual DbSet<LANGUAGES> LANGUAGES { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<PAYMENT_METHOD> PAYMENT_METHOD { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PRODUCT_TRANSLATION> PRODUCT_TRANSLATION { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SHOP> SHOP { get; set; }
        public virtual DbSet<SHOP_PRODUCT> SHOP_PRODUCT { get; set; }
        public virtual DbSet<SHOP_TRANSLATION> SHOP_TRANSLATION { get; set; }
        public virtual DbSet<SUBCATEGORY> SUBCATEGORY { get; set; }
        public virtual DbSet<TERMINAL> TERMINAL { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<TICKET_MESSAGE> TICKET_MESSAGE { get; set; }
        public virtual DbSet<TICKET_MESSAGE_TRANSLATION> TICKET_MESSAGE_TRANSLATION { get; set; }
        public virtual DbSet<TRANSACTION_DETAILS> TRANSACTION_DETAILS { get; set; }
        public virtual DbSet<TRANSACTIONS> TRANSACTIONS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<VAT> VAT { get; set; }
    }
}
