//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPOS2.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS_MESSAGE
    {
        public int transactionId { get; set; }
        public int messageId { get; set; }
        public int languageMessage { get; set; }
    
        public virtual MESSAGE MESSAGE { get; set; }
        public virtual TRANSACTIONS TRANSACTIONS { get; set; }
    }
}
